spring:
  application:
    name: catalog-service
    data:
    mongodb:
      host: catalog-database
      username: catalog
      password: catalog
      port: 27017
      database: catalog_database
  zipkin:
    base-url: http://zipkin-server:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-server
    port: 5672

server:
  port: 8081

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    LeaseExpirationDurationInSeconds: 10
