spring:
  application:
    name: serie-service
  data:
    mongodb:
      host: series-database
      username: series
      password: series
      port: 27018
      database: series_database
  zipkin:
    base-url: http://zipkin-server:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq-server
    port: 5672

server:
  port: 8092

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    LeaseExpirationDurationInSeconds: 10
