spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  instance:
    preferIpAddress: true